name: Luacheck

on: [push]

jobs:
  luacheck:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run Luacheck
      uses: lunarmodules/luacheck@v0
      with:
        path: main.lua
        args: "--ignore | -i undefined"