name: Upload Addon to CurseForge
on:
  push:
    #branches:
    #  - main
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Determine version number
        id: version
        run: |
          # Extract the version number from the TOC file
          version=$(grep -oP 'Version: \Kv\d+\.\d+\.\d+' AvgItemLvl.toc)
    
          # Extract the minor version number
          minor_version=$(echo "$version" | cut -d "." -f 2)
          
          # Increment the minor version number
          next_minor_version=$((minor_version + 1))
          
          # Print the new version number
          echo "New version: $(echo "$version" | cut -d "." -f 1).$next_minor_version.$(echo "$version" | cut -d "." -f 3)"
          
          # Set the output for the version number
          echo "::set-output name=version::$(echo "$version" | cut -d "." -f 1).$next_minor_version.$(echo "$version" | cut -d "." -f 3)"
          
      - name: Create version tag
        run: |
          # Get the new version number
          new_version=$(echo "::set-output name=version::$(echo "$version" | cut -d "." -f 1).$next_minor_version.$(echo "$version" | cut -d "." -f 3)")
          
          # Create a new tag for the current commit
          git tag "$new_version"
          git tag -d "$new_version"
          
          # Push the new tag to the repository
          #git push origin "$new_version"



      # - name: Update addon TOC file
      #   run: sed -i "s/^Version:.*\$/Version: ${{ steps.minor-version.outputs.minor-version }}/" AvgItemLvl.toc

      # - name: Zip repository contents
      #   run: zip -r AvgItemLvl-${{ steps.minor-version.outputs.minor-version }}.zip .
      
      # - name: Upload Addon to CurseForge
      #   uses: Lcfvs/upload-to-curseforge-action@v1.0.0
      #   with:
      #     api-token: ${{ secrets.CURSEFORGE_API_TOKEN }}
      #     addon-id: ${{ secrets.CURSEFORGE_ADDON_ID }}
      #     addon-file: AvgItemLvl-${{ steps.minor-version.outputs.minor-version }}.zip

      # - name: Delete addon zip file
      #   run: rm AvgItemLvl-${{ steps.minor-version.outputs.minor-version }}.zip
