name: Upload Addon to CurseForge
on:
  push:
    branches:
      - main
jobs:
  upload:
    runs-on: ubuntu-latest
    outputs:
      verion: ${{ steps.determine_version_number.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Determine version number
        id: version
        run: |
          # Extract the version number from the TOC file
          updated_version=$(grep -oP 'Version: \Kv\d+\.\d+\.\d+' AvgItemLvl.toc)

          # Store the version number in an output variable
          echo "version=$updated_version" >> $GITHUB_OUTPUT
          echo "${{ steps.determine_version_number.outputs.version }}"
          
      - name: Create version tag
        run: |
          # Retrieve the version number from the output variable
          version=${{ steps.determine_version_number.outputs.version }}
          
          # Create a new tag for the current commit 
          git tag $version
          
          # Push the new tag to the repository
          git push origin $version

      - name: Zip repository contents
        run: |
          # Retrieve the version number from the output variable
          version=${{ steps.determine_version_number.outputs.version }}
          
          zip -r AvgItemLvl-$version.zip .
      
      - name: Upload Addon to CurseForge
        uses: itsmeow/curseforge-upload@v3
        with:
          token: ${{ secrets.CURSEFORGE_API_TOKEN }}
          project_id: ${{ secrets.CURSEFORGE_ADDON_ID }}
          game_endpoint: "wow"
          release_type: release
          changelog: "${{ steps.determine_version_number.outputs.version }} update"
          file_path: AvgItemLvl-${{ steps.determine_version_number.outputs.version }}.zip
