name: Upload Addon to CurseForge
on:
  push:
    branches:
      - main
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Determine version number
        id: version
        run: |
          # Extract the version number from the TOC file
          version=$(grep -oP 'Version: \Kv\d+\.\d+\.\d+' AvgItemLvl.toc)
    
          # Extract the minor version number
          minor_version=$(echo "$version" | cut -d "." -f 2)
          
          # Increment the minor version number
          next_minor_version=$((minor_version + 1))
          
          # Print the new version number
          echo "New version: $(echo "$version" | cut -d "." -f 1).$next_minor_version.$(echo "$version" | cut -d "." -f 3)"
          
          # Set the output for the version number
          echo "::set-output name=version::$(echo "$version" | cut -d "." -f 1).$next_minor_version.$(echo "$version" | cut -d "." -f 3)"
          
      - name: Create version tag
        run: |
          # Get the new version number
          new_version=${{ steps.version.outputs.version }}
          
          # Create a new tag for the current commit
          git tag ${{ steps.version.outputs.version }}
          git tag -d ${{ steps.version.outputs.version }}
          
          # Push the new tag to the repository
          #git push origin ${{ steps.version.outputs.version }}

      - name: Update addon TOC file and push version changes
        run: |
          sed -i "s/^Version:.*\$/Version: ${{ steps.version.outputs.version }}/" AvgItemLvl.toc
          
          # Commit changes to the repository
          git config --local user.email "magiaco92@gmail.com"
          git config --local user.name "GitHub Action"
          git add AvgItemLvl.toc
          git commit -m "Update TOC version to ${{ steps.version.outputs.version }}"
          git push

      - name: Zip repository contents
        run: zip -r AvgItemLvl-${{ steps.version.outputs.version }}.zip .
      
      - name: Upload Addon to CurseForge
        uses: itsmeow/curseforge-upload@v3
        with:
          token: ${{ secrets.CURSEFORGE_API_TOKEN }}
          project_id: ${{ secrets.CURSEFORGE_ADDON_ID }}
          game_endpoint: "wow"
          release_type: release
          changelog: "${{ steps.version.outputs.version }} update"
          file_path: AvgItemLvl-${{ steps.version.outputs.version }}.zip