name: Upload Addon to CurseForge
on:
  push:
    branches:
      - main
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Determine version number
        id: latest_version
        run: |
          # Extract the version number from the TOC file
          latest_version=$(grep -oP 'Version: \Kv\d+\.\d+\.\d+' AvgItemLvl.toc)
          echo $latest_version
          # Store the version number in an output variable
          echo "v=$latest_version" >> $GITHUB_ENV
          echo $v
          
      - name: Create version tag
        run: |
          # Create a new tag for the current commit 
          git tag $v
          
          # Push the new tag to the repository
          git push origin $v

      - name: Zip repository contents
        run: |
          zip -r AvgItemLvl-$v.zip .
      
      - name: Upload Addon to CurseForge
        uses: itsmeow/curseforge-upload@v3
        with:
          token: ${{ secrets.CURSEFORGE_API_TOKEN }}
          project_id: ${{ secrets.CURSEFORGE_ADDON_ID }}
          game_endpoint: "wow"
          release_type: release
          changelog: "$v update"
          file_path: AvgItemLvl-$v.zip
