name: Upload Addon to CurseForge
on:
  push:
    branches:
      - main
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Determine version number
        run: |
          # Extract the version number from the TOC file
          updated_version=$(grep -oP 'Version: \Kv\d+\.\d+\.\d+' AvgItemLvl.toc)

          # Store the version number in an output variable
          echo "version=$updated_version" >> $GITHUB_ENV
          echo ${{ env.version }}
          
      - name: Create version tag
        run: |
          # Create a new tag for the current commit 
          git tag ${{ env.version }}
          
          # Push the new tag to the repository
          git push origin ${{ env.version }}

      - name: Zip repository contents
        run: |
          zip -r AvgItemLvl-${{ env.version }}.zip .
      
      - name: Upload Addon to CurseForge
        uses: itsmeow/curseforge-upload@v3
        with:
          token: ${{ secrets.CURSEFORGE_API_TOKEN }}
          project_id: ${{ secrets.CURSEFORGE_ADDON_ID }}
          game_endpoint: "wow"
          release_type: release
          changelog: "${{ env.version }} update"
          file_path: AvgItemLvl-${{ env.version }}.zip
