name: Upload Addon to CurseForge
on:
  push:
    #branches:
    #  - main
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Determine version number
        id: version
        run: |
          # Extract the version number from the TOC file
          version=$(grep -oP 'Version: \Kv\d+\.\d+\.\d+' AvgItemLvl.toc)
    
          # Extract the minor version number
          minor_version=$(echo "$version" | cut -d "." -f 2)
          
          # Increment the minor version number
          next_minor_version=$((minor_version + 1))
          
          # Print the new version number
          echo "New version: v$(echo "$version" | cut -d "." -f 1).$next_minor_version.$(echo "$version" | cut -d "." -f 3)"
          echo "New version number: $new_version"
          
          # Set the output for the version number
          echo "::set-output name=version::v$(echo "$version" | cut -d "." -f 1).$next_minor_version.$(echo "$version" | cut -d "." -f 3)"

      # - name: Increment minor version number
      #   id: minor-version
      #   run: echo "::set-output name=minor-version::$(echo ${{ steps.version.outputs.version }} | awk -F '.' '{print $1"."$2"."$3+1}')"

      # - name: Create new version tag
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: ${{ steps.minor-version.outputs.minor-version }}
      #     name: ${{ steps.minor-version.outputs.minor-version }}
      #     draft: false
      #     prerelease: false

      # - name: Update addon TOC file
      #   run: sed -i "s/^Version:.*\$/Version: ${{ steps.minor-version.outputs.minor-version }}/" AvgItemLvl.toc

      # - name: Zip repository contents
      #   run: zip -r AvgItemLvl-${{ steps.minor-version.outputs.minor-version }}.zip .
      
      # - name: Upload Addon to CurseForge
      #   uses: Lcfvs/upload-to-curseforge-action@v1.0.0
      #   with:
      #     api-token: ${{ secrets.CURSEFORGE_API_TOKEN }}
      #     addon-id: ${{ secrets.CURSEFORGE_ADDON_ID }}
      #     addon-file: AvgItemLvl-${{ steps.minor-version.outputs.minor-version }}.zip

      # - name: Delete addon zip file
      #   run: rm AvgItemLvl-${{ steps.minor-version.outputs.minor-version }}.zip
