name: Upload Addon to CurseForge
on:
  push:
    branches:
      - main
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Determine version number
        id: latest_version
        run: |
          # Extract the version number from the TOC file
          echo "::set-output name=v::$(grep -oP 'Version: \Kv\d+\.\d+\.\d+' AvgItemLvl.toc)"

        env:
          v: ${{ steps.latest_version.outputs.v }}
      - name: Create version tag
        run: |
          # Create a new tag for the current commit 
          git tag ${{ steps.latest_version.outputs.v }}

          # Push the new tag to the repository
          git push origin ${{ steps.latest_version.outputs.v }}
        env:
          v: ${{ steps.latest_version.outputs.v }}
      - name: Zip repository contents
        run: |
          zip -r AvgItemLvl-${{ steps.latest_version.outputs.v }}.zip .

      - name: Upload Addon to CurseForge
        uses: itsmeow/curseforge-upload@v3
        with:
          token: ${{ secrets.CURSEFORGE_API_TOKEN }}
          project_id: ${{ secrets.CURSEFORGE_ADDON_ID }}
          game_endpoint: "wow"
          release_type: release
<<<<<<< HEAD
          changelog: "${{ steps.latest_version.outputs.v }} update"
          file_path: AvgItemLvl-${{ steps.latest_version.outputs.v }}.zip
=======
          changelog: "${{ steps.determine_version_number.outputs.version }} update"
          file_path: AvgItemLvl-${{ steps.determine_version_number.outputs.version }}.zip
>>>>>>> 17fe4895f876607a627ef6a47a42ce7730fdd6b7
